version: "3"
services:
  mysql_master:
    image: mysql
    user: root
    build:
      context: ./mysql_master
      dockerfile: Dockerfile
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.10
    container_name: mysql_master
    restart: always

  mysql_slave:
    image: mysql
    build:
      context: ./mysql_slave
      dockerfile: Dockerfile
    env_file: .env
    user: root
    stdin_open: true
    tty: true
    ports:
      - 3307:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.11
    depends_on:
      - mysql_master
    container_name: mysql_slave

  myredis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
    networks:
      - dock_net

  springbootapp:
    build: .
    container_name: springbootapp
    ports:
      - "5000:9090"
    depends_on:
      - mysql_master
      - mysql_slave
      - myredis
    restart: always
    networks:
      - dock_net
networks:
  dock_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
