version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - docker_net
    restart: always

  myredis:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
    networks:
      - docker_net

  springbootapp:
    build: .
    container_name: springbootapp
    ports:
      - "5000:9090"
    depends_on:
      - mysql
      - myredis
    restart: always
    networks:
      - docker_net
networks:
  docker_net:
    driver: bridge
    name: docker_net
